
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Mar 03 22:10:34 CST 2019
//----------------------------------------------------

package AnalizadorGxml;

/** CUP generated class containing symbol constants. */
public class symGxml {
  /* terminals */
  public static final int etq_datos = 11;
  public static final int abrir = 2;
  public static final int atb_tam = 29;
  public static final int textoXml = 4;
  public static final int cerrar = 40;
  public static final int igual = 38;
  public static final int etq_defecto = 12;
  public static final int atb_tipo = 18;
  public static final int atb_auto_reprodu = 37;
  public static final int atb_color = 19;
  public static final int etq_texto = 8;
  public static final int atb_id = 17;
  public static final int atb_minimo = 33;
  public static final int atb_path = 36;
  public static final int etq_control = 9;
  public static final int etq_boton = 14;
  public static final int atb_accioninicial = 20;
  public static final int numero = 41;
  public static final int etq_importar = 5;
  public static final int atb_y = 23;
  public static final int etq_listadatos = 10;
  public static final int atb_x = 22;
  public static final int EOF = 0;
  public static final int verdadero = 42;
  public static final int atb_borde = 26;
  public static final int error = 1;
  public static final int atb_accion = 34;
  public static final int etq_multimedia = 13;
  public static final int atb_maximo = 32;
  public static final int etq_contenedor = 7;
  public static final int etq_ventana = 6;
  public static final int atb_cursiva = 31;
  public static final int atb_negrita = 30;
  public static final int abrird = 3;
  public static final int falso = 43;
  public static final int atb_ancho = 25;
  public static final int atb_alto = 24;
  public static final int codigo = 16;
  public static final int atb_accionfinal = 21;
  public static final int atb_referencia = 35;
  public static final int atb_fuente = 28;
  public static final int etq_enviar = 15;
  public static final int exp_id = 44;
  public static final int cadenaXml = 39;
  public static final int atb_nombre = 27;
}

