/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package creatorxml;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

/**
 *
 * @author ivanl
 */
public class Errores extends javax.swing.JFrame {

    /**
     * Creates new form Errores
     */
    public Errores() {
        initComponents();
        addWindowListener(new WindowAdapter() {
            
            @Override
            public void windowClosing(WindowEvent e) {
                //Hacer lo que yo quiero
                System.out.println("Estoy cerrando");
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane2 = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jEditorPane2.setContentType("text/html"); // NOI18N
        jEditorPane2.setText("<html> \t<head> \t\t<title>Tabla de Simbolos</title><meta charset=\"utf-8\"> \t\t<link rel=\"stylesheet\"type=\"text/css\" href=\"Estilo.css\"> \t</head> \t<body> \t\t<div style=\"text-align:left;\"> \t\t\t<h1>TABLA DE SIMBOLOS</h1> \t\t\t<h2>Dia de ejecución:20 de Marzo de 2019</h2> \t\t\t<h2>Hora de ejecución:17:52:28 p.m.</h2> \t\t\t<table style=\"margin: margin: 5 auto;\" border=\"2\"> \t\t\t\t<TR> \t\t\t\t\t<TH>Clase Ejecucion</TH> <TH>Tipo</TH> <TH>ambito</TH> <TH>error</TH> <TH>linea</TH><TH>columna</TH> \t\t\t\t</TR> \t\t\t\t<TR> \t\t\t\t\t<TD>Sintactico Gxml</TD><TD>sintactico</TD><TD>sintactico</TD><TD>el token \"base\" no es valida </TD><TD>1</TD><TD>17</TD> \t\t\t\t</TR> \t\t\t\t<TR> \t\t\t\t\t<TD>Sintactico Gxml</TD><TD>sintactico</TD><TD>sintactico</TD><TD>el token \"clasificacion\" no es valida </TD><TD>1</TD><TD>16</TD> \t\t\t\t</TR> \t\t\t\t<TR> \t\t\t\t\t<TD>Sintactico Gxml</TD><TD>sintactico</TD><TD>sintactico</TD><TD>el token \"tipo\" no es valida </TD><TD>35</TD><TD>17</TD> \t\t\t\t</TR> \t\t\t\t<TR> \t\t\t\t\t<TD>Sintactico Gxml</TD><TD>sintactico</TD><TD>sintactico</TD><TD>el token \"discos\" no es valida </TD><TD>1</TD><TD>14</TD> \t\t\t\t</TR> \t\t\t\t<TR> \t\t\t\t\t<TD>Sintactico Gxml</TD><TD>sintactico</TD><TD>sintactico</TD><TD>el token \"item\" no es valida </TD><TD>35</TD><TD>27</TD> \t\t\t\t</TR> \t\t\t</table> \t\t</div> \t</body> </html>   ");
        jScrollPane2.setViewportView(jEditorPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 931, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 13, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setText(String texto) {

        jEditorPane2.setText(texto);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Errores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Errores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Errores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Errores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Errores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane jEditorPane2;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
