
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Mar 15 00:52:37 CST 2019
//----------------------------------------------------

package AnalizadorFs;

/** CUP generated class containing symbol constants. */
public class symFs {
  /* terminals */
  public static final int t_true = 36;
  public static final int igualigual = 26;
  public static final int maximo = 42;
  public static final int porigual = 58;
  public static final int menosigual = 57;
  public static final int imprimir = 9;
  public static final int t_false = 37;
  public static final int mayorq = 22;
  public static final int alguno = 51;
  public static final int detener = 10;
  public static final int dividir = 31;
  public static final int coma = 8;
  public static final int divigual = 59;
  public static final int igual = 7;
  public static final int ternario = 52;
  public static final int reduce = 47;
  public static final int ascendente = 41;
  public static final int llavec = 14;
  public static final int masigual = 56;
  public static final int llavea = 13;
  public static final int menosmenos = 34;
  public static final int si = 17;
  public static final int puntoycoma = 5;
  public static final int importar = 2;
  public static final int defecto = 49;
  public static final int numero = 38;
  public static final int masmas = 33;
  public static final int buscar = 45;
  public static final int menos = 29;
  public static final int var = 6;
  public static final int EOF = 0;
  public static final int mas = 28;
  public static final int parentesisc = 4;
  public static final int menorq = 23;
  public static final int error = 1;
  public static final int parentesisa = 3;
  public static final int map = 46;
  public static final int or = 19;
  public static final int menorigual = 25;
  public static final int por = 30;
  public static final int punto = 39;
  public static final int funcion = 53;
  public static final int dospuntos = 16;
  public static final int filter = 44;
  public static final int invertir = 43;
  public static final int id = 35;
  public static final int potencia = 32;
  public static final int caso = 15;
  public static final int mayorigual = 24;
  public static final int minimo = 60;
  public static final int todos = 48;
  public static final int diferente = 27;
  public static final int corchetec = 55;
  public static final int and = 20;
  public static final int not = 21;
  public static final int corchetea = 54;
  public static final int descendente = 40;
  public static final int retornar = 11;
  public static final int selecciona = 12;
  public static final int cadena = 50;
  public static final int sino = 18;
}

