
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Mar 20 20:30:11 CST 2019
//----------------------------------------------------

package AnalizadorFs.gdato;

/** CUP generated class containing symbol constants. */
public class symGdato {
  /* terminals */
  public static final int etq_lista = 4;
  public static final int exp_id = 9;
  public static final int abrir = 2;
  public static final int abrird = 3;
  public static final int cadenaXml = 6;
  public static final int EOF = 0;
  public static final int etq_principal = 5;
  public static final int numero = 8;
  public static final int error = 1;
  public static final int cerrar = 7;
}

